import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 border-b">
          <div className="max-w-4xl mx-auto flex gap-4">
            <Link href="/" className="hover:text-foreground/80">
              Home
            </Link>
            <Link href="/about" className="hover:text-foreground/80">
              About
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}

